### ISSUE TITLE
any ways to control the pitch?

### ISSUE THREAD

**Issue by raveslave** [Deep-Symmetry/beat-link#31]
wanna remote control the pitch. doable?

**Comment by brunchboy** [comment]
No, there is no evidence of such an option. If you find any such evidence, though, please share it!

**Comment by brunchboy** [comment]
Actually, wait… You mean you want to set the tempo of a player? You can do that now, yes, by having Beat Link become the tempo master. Please ask on the [Beat Link Trigger Gitter channel](https://gitter.im/brunchboy/beat-link-trigger)

**Comment by raveslave** [comment]
ah true, that's right..! so play, stop, pitch doable.. but not Cue and nudge/slip (same as touching the platter)

**Comment by brunchboy** [comment]
Right, check out the [`becomeTempoMaster` method](
http://deepsymmetry.org/beatlink/apidocs/org/deepsymmetry/beatlink/VirtualCdj.html#becomeTempoMaster--) of the `VirtualCdj`, along with [`setTempo`](http://deepsymmetry.org/beatlink/apidocs/org/deepsymmetry/beatlink/VirtualCdj.html#setTempo-double-)

**Comment by brunchboy** [comment]
Play and stop are somewhat doable, but play only works if the player is paused at the cue point, and you can only adjust the tempo by acting as the tempo master. The protocol is not designed to support general remote control.

**Comment by brunchboy** [comment]
You can probably nudge to the nearest beat by calling [`jumpToBeat`](
http://deepsymmetry.org/beatlink/apidocs/org/deepsymmetry/beatlink/VirtualCdj.html#jumpToBeat-int)- but that is the closest I can think of.

**Comment by brunchboy** [comment]
Out of curiosity, what are you building?

**Comment by raveslave** [comment]
Many thanks for input! will experiment and see how it works. Depending on how quick setTempo is, that could probably be used to momentarily push the bpm a bit, i.e. to do the equivalent of nudging the platter with your hand.

I was first thinking about pathing the button PCB to get full access, but would be a time-saver to make it all via the ethernet protocol.

...building a simplified, physical remote to control one or many cdj's ☃

**Comment by brunchboy** [comment]
Interesting! Best of luck with that. Another avenue you may want to pursue is the USB interface, I believe there are elements of remote control via that in order to support use with a controller and as a HID input to integrated DJ software. If you have access to a USB sniffer and the other pieces to try this out you may find more powerful approaches you can use.
