### ISSUE TITLE
CrateDigger can use an invalid cache if a USB is changed whilst a player is unplugged

### ISSUE THREAD

**Issue by ben-xo** [Deep-Symmetry/beat-link#38]
Okay bear with me - this is rather an edge case. But I have a solution to propose.

Steps to reproduce
* start CrateDigger 
* let it load details from a USB
* unplug CDJ from network (observe
```
   INFO [AWT-EventQueue-0] (MetadataFinder.java:887) - Reporting media removed from SlotReference[player:2, slot:CD_SLOT]
   INFO [AWT-EventQueue-0] (CrateDigger.java:154) - Ignoring unmount from player that we can't find, must have left network.
   INFO [AWT-EventQueue-0] (MetadataFinder.java:887) - Reporting media removed from SlotReference[player:2, slot:USB_SLOT]
   INFO [AWT-EventQueue-0] (CrateDigger.java:154) - Ignoring unmount from player that we can't find, must have left network.
```
* whilst unplugged put a new USB in
* reconnect CDJ
* observe
```
INFO [AWT-EventQueue-0] (MetadataFinder.java:351) - Processing device found, number:2, name:"CDJ-2000".
INFO [Thread-2] (MetadataFinder.java:884) - Reporting media mounted in SlotReference[player:2, slot:USB_SLOT]
INFO [Thread-2] (MetadataFinder.java:884) - Reporting media mounted in SlotReference[player:2, slot:CD_SLOT]
```
* observe no refresh of CrateDigger cache
* songs with the same ID on that USB will have wrong metadata.

EXPECTED
* cache is refreshed when CDJ joins with a new USB.

CAUSE
looking at the code, CrateDigger essentially ignores mediaUnmounted events when it can't look up the player associated with the slot (in order to remove it from the FileFetcher) - presumably as it's already been removed from DeviceFinder too.

PROPOSED SOLUTION
it looks like almost all of the code in CrateDigger#mediaUnmounted() does not actually depend on getting slot.player and could be processed outside of the if() block. The consequence of not removing the mount from FileFetcher's cache should be minimal as it will be updated again when the device returns.

**Comment by brunchboy** [comment]
Nice catch! I moved this to the Beat Link repository, because that is where the problem is actually taking place (in the `CrateDigger` class of Beat Link, which is in charge of managing Crate Digger in response to things it sees happening on the DJ Link network).

I just didn’t consider that this race condition might occur, but you are right, it doesn’t matter if we can’t find the player any more, we should dump the cache regardless.

**Comment by brunchboy** [comment]
I will have to keep a copy of the address around to handle this.

**Comment by brunchboy** [comment]
Could you give the latest beat-link` 0.5.6-SNAPSHOT` a try and see if this addresses the issue in your environment?

**Comment by ben-xo** [comment]
So far so good…! I can no longer reproduce the problem... so i'd say fixed!

**Comment by brunchboy** [comment]
Thanks for the validation! 🎉
