### ISSUE TITLE
Support starting VirtualCdj on a different network interface 

### ISSUE THREAD

**Issue by aphexcx** [Deep-Symmetry/beat-link#43]
**Is your feature request related to a problem? Please describe.**
I really want to get beat-link working on the *same machine* as rekordbox. This is because I stream live on twitch (https://twitch.tv/aphexcx) and I use beat-link to show live track metadata as I mix. 

Check out this video for an example: https://youtu.be/uyb__t70EC4?t=2082

(If you want to do that too, my code for getting track metadata displayed in OBS is here! https://github.com/aphexcx/dj-link-now-playing)

This of course means I can't run rekordbox on my machine and my beat-link code at the same time, because VirtualCdj can't start if rekordbox is running. It'll complain with :
```
Exception in thread "main" java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainDatagramSocketImpl.bind0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
	at java.net.DatagramSocket.bind(DatagramSocket.java:392)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
	at org.deepsymmetry.beatlink.VirtualCdj.createVirtualCdj(VirtualCdj.java:902)
	at org.deepsymmetry.beatlink.VirtualCdj.start(VirtualCdj.java:1040)
	at org.deepsymmetry.beatlink.data.MetadataFinder.start(MetadataFinder.java:1454)
```

**Describe the solution you'd like**
I want to be able to start the VirtualCdj on a different network interface. For example, my computer is connected to my network via a LAN connection *and* WiFi. I want to be able to run rekordbox on my LAN network interface and start the VirtualCdj on the Wifi network interface.

**Describe alternatives you've considered**
I've cloned the repo and spent a few hours hacking up the `createVirtualCdj()` function in VirtualCdj.java to get this working. I've gotten as far as seeing the two different network interfaces when it's running, and then I hardcoded it to use the interface and address associated with my WiFi interface. However, strangely, I still get the BindException above when the socket attempts to set.

I am not sure why. I even switched things around, and made sure rekordbox is running on my WiFi interface (by disconnected the LAN cable and starting the rekordbox LINK feature), and *then* reconnected the LAN cable and tried to start the VirtualCdj using the LAN address. Still says the address is in use. 

FWIW, after inspecting a little bit with my debugger, it appears both interfaces available on my machine seem to have the same *broadcast address*. Could this be the issue?

**Comment by brunchboy** [comment]
I’m sorry, but what you are trying to do is simply not possible. It’s just not the way IP networking works, combined with unfortunate choices made in creating the DJ Link protocol. I would recommend buying a fairly inexpensive Raspberry Pi to run Beat Link Trigger, or seeing if you could get it (or rekordbox) working inside a virtual machine. I know the Pi approach works, I have done it. I have not heard of anyone having success with a virtual machine, so you would be a bit more on your own there. If you do get that working, writing up how would be helpful to others in the future, and you could share it on the wiki.

**Comment by aphexcx** [comment]
I understand that isn't possible on the *same* interface, but seeing as my computer has two network interfaces with distinct ip address, wouldn't that mean it's possible?

**Comment by brunchboy** [comment]
Also note that if you have two networking interfaces on the same network, it will cause problems for the CDJs because of duplicate broadcast packets reaching them. It often even leads to the players freezing in emergency loops. This is why Beat Link Trigger tries to warn you if it detects this problem.

**Comment by brunchboy** [comment]
No, it’s not the interface that is the problem, it is the network. A TCP port is defined by a combination of IP address and port, so if DJ link only used direct addressing, you could maybe get this to work, given that the interface used by rekordbox and the one used by Beat Link could be assigned different IP addresses. But the DJ link protocol relies on _broadcast_ packets, which do not have their own IP addresses.

**Comment by brunchboy** [comment]
So because only one process on a given host can bind to the broadcast address on a given network, only one of Beat Link and rekordbox can operate at once. Binding to a broadcast address binds _all_ network interfaces that are connected to that network.

**Comment by brunchboy** [comment]
This is why I say it might be possible to solve this by using virtual machines; they are running their own operating systems, and may be able to pull this off. I haven’t heard of anyone succeeding, but if you do I’d love to know. 😄

**Comment by aphexcx** [comment]
Oy vey, I didn't know that about broadcast addresses. Really appreciate you for explaining. I suppose I'll try and get my code running on another machine on the network -- and figure out how to get OBS to still display the metadata it gleans.

**Comment by brunchboy** [comment]
Yeah, it frustrated me quite a bit when I ran into it myself! Sorry. Good luck! OBS should be able to talk over the network.

**Comment by brunchboy** [comment]
(As an aside which might amuse you, it turns out this bit Pioneer DJ themselves when they created the XDJ-XZ. I couldn’t figure out some weird things about the way they implemented DJ link for that device until I realized that because it is a single host on the network it has the same problem, it can only run one instance of the DJ Link protocol, so it has to do things like pretending that its two USB slots are an SD and USB slot on a single player, and adding new fields to let rekordbox tell it which player it wants to have load a track.)
