### ISSUE TITLE
More hot cue color table values

### ISSUE THREAD

**Issue by mganss** [Deep-Symmetry/beat-link#51]
I've identified more hot cue color table values. You can't select them through the Rekordbox UI but they work nonetheless if you set these values in the database. All values above 0x3e (62) come out black. Since these colors can't be set through the UI their real world value is probably limited, so feel free to just close this.

```java
case 0x00: return new Color(0x28, 0xe2, 0x14);
case 0x01: return new Color(0x30, 0x5a, 0xff);
case 0x02: return new Color(0x50, 0x73, 0xff);
case 0x03: return new Color(0x50, 0x8c, 0xff);
case 0x04: return new Color(0x50, 0xa0, 0xff);
case 0x05: return new Color(0x50, 0xb4, 0xff);
case 0x06: return new Color(0x50, 0xb0, 0xf2);
case 0x07: return new Color(0x50, 0xae, 0xe8);
case 0x08: return new Color(0x45, 0xac, 0xdb);
case 0x09: return new Color(0x00, 0xe0, 0xff);
case 0x0a: return new Color(0x19, 0xda, 0xf0);
case 0x0b: return new Color(0x32, 0xd2, 0xe6);
case 0x0c: return new Color(0x21, 0xb4, 0xb9);
case 0x0d: return new Color(0x20, 0xaa, 0xa0);
case 0x0e: return new Color(0x1f, 0xa3, 0x92);
case 0x0f: return new Color(0x19, 0xa0, 0x8c);
case 0x10: return new Color(0x14, 0xa5, 0x84);
case 0x11: return new Color(0x14, 0xaa, 0x7d);
case 0x12: return new Color(0x10, 0xb1, 0x76);
case 0x13: return new Color(0x30, 0xd2, 0x6e);
case 0x14: return new Color(0x37, 0xde, 0x5a);
case 0x15: return new Color(0x3c, 0xeb, 0x50);
case 0x16: return new Color(0x28, 0xe2, 0x14);
case 0x17: return new Color(0x7d, 0xc1, 0x3d);
case 0x18: return new Color(0x8c, 0xc8, 0x32);
case 0x19: return new Color(0x9b, 0xd7, 0x23);
case 0x1a: return new Color(0xa5, 0xe1, 0x16);
case 0x1b: return new Color(0xa5, 0xdc, 0x0a);
case 0x1c: return new Color(0xaa, 0xd2, 0x08);
case 0x1d: return new Color(0xb4, 0xc8, 0x05);
case 0x1e: return new Color(0xb4, 0xbe, 0x04);
case 0x1f: return new Color(0xba, 0xb4, 0x04);
case 0x20: return new Color(0xc3, 0xaf, 0x04);
case 0x21: return new Color(0xe1, 0xaa, 0x00);
case 0x22: return new Color(0xff, 0xa0, 0x00);
case 0x23: return new Color(0xff, 0x96, 0x00);
case 0x24: return new Color(0xff, 0x8c, 0x00);
case 0x25: return new Color(0xff, 0x75, 0x00);
case 0x26: return new Color(0xe0, 0x64, 0x1b);
case 0x27: return new Color(0xe0, 0x46, 0x1e);
case 0x28: return new Color(0xe0, 0x30, 0x1e);
case 0x29: return new Color(0xe0, 0x28, 0x23);
case 0x2a: return new Color(0xe6, 0x28, 0x28);
case 0x2b: return new Color(0xff, 0x37, 0x6f);
case 0x2c: return new Color(0xff, 0x2d, 0x6f);
case 0x2d: return new Color(0xff, 0x12, 0x7b);
case 0x2e: return new Color(0xf5, 0x1e, 0x8c);
case 0x2f: return new Color(0xeb, 0x2d, 0xa0);
case 0x30: return new Color(0xe6, 0x37, 0xb4);
case 0x31: return new Color(0xde, 0x44, 0xcf);
case 0x32: return new Color(0xde, 0x44, 0x8d);
case 0x33: return new Color(0xe6, 0x30, 0xb4);
case 0x34: return new Color(0xe6, 0x19, 0xdc);
case 0x35: return new Color(0xe6, 0x00, 0xff);
case 0x36: return new Color(0xdc, 0x00, 0xff);
case 0x37: return new Color(0xcc, 0x00, 0xff);
case 0x38: return new Color(0xb4, 0x32, 0xff);
case 0x39: return new Color(0xb9, 0x3c, 0xff);
case 0x3a: return new Color(0xc5, 0x42, 0xff);
case 0x3b: return new Color(0xaa, 0x5a, 0xff);
case 0x3c: return new Color(0xaa, 0x72, 0xff);
case 0x3d: return new Color(0x82, 0x72, 0xff);
case 0x3e: return new Color(0x64, 0x73, 0xff);
```

**Comment by brunchboy** [comment]
Interesting! I wonder what the idea is behind the other colors? I don’t see any harm in supporting them even if the current UI doesn’t offer them. I’m a bit swamped with other things right now, but I will add these soon, thanks.

**Comment by mganss** [comment]
Perhaps they had initially planned on surfacing more than 16 colors or maybe they're using only a subset of a feature their platform (Unity) offers?
I find it strange that they have totally different concepts of color for memory cues and hot cues. Memory cues share the same set of 8 colors with track colors while the set of hot cue colors is completely disjoint.

**Comment by mganss** [comment]
I think I know what the other colors are for: In rekordbox preferences under View -> Color -> HOT CUE you can choose from 4 color schemes:
- CDJ
- COLD1
- COLD2
- COLORFUL

If CDJ is selected, all hot cues are colored green by default (color index 0). Selecting one of the other color schemes results in hot cues getting individual colors according to their number (A to P). These colors come from the color table above.

The palette of 16 colors from which you can select individual colors is not affected by this choice and hot cues which you have assigned an individual color keep that color if you switch color schemes in preferences.

**Comment by brunchboy** [comment]
Cool, I am incorporating this table. There were some small differences for values I already had in there, but your list is likely more definitive. How did you find it?

**Comment by mganss** [comment]
I manually re-checked the differences to your original table: the new values are correct.

I found the table the hard way by changing the color index value of hot cues in the rekordbox SQLite database to all values between 0 and 255 (using a script), then making screenshots and checking the actual colors using GIMP's color picker. I did this as part of a crazy little project that generates rekordbox cue points from Mixed in Key cue points: https://github.com/mganss/CueGen

**Comment by brunchboy** [comment]
Thanks for being so thorough! That sounds like a neat project.
