### ISSUE TITLE
Support Opus based on findings from https://github.com/kyleawayan/opus-quad-pro-dj-link-analysisx

### ISSUE THREAD

**Issue by cprepos** [Deep-Symmetry/beat-link#68]
**Is your feature request related to a problem? Please describe.**
Opus Quad seems to be sending out packet information that will at least provide minimal use to beat-link/beat-link-trigger users (like myself). Big ups to kyleawayan for doing a lot of research to prove this. 

**Describe the solution you'd like**
I would like to use the above new findings to enhance beat-link to provide whatever limited functionality it can from the opus. Looks like track metadata and opus CDJ Statuses are made available via port 50002 after sending a specific announce packet to both 50000 and 50002. 

Specific features:
Enhance existing features where possible to accept Opus quad signals from 50002. Would love if it could plug into existing shows using track IDs and CDJ statuses it broadcasts. This functionality would be super useful for those that can program shows using proper CDJs but use those shows with the Opus. Phrase information would also be awesome. 

**Describe alternatives you've considered**
I dont see any other alternatives

**Additional context**
https://github.com/kyleawayan/opus-quad-pro-dj-link-analysis

**Comment by cprepos** [comment]
I am making an attempt at setting this up. I have not worked with UDP packet signals in the past so it might take some time to ramp up.

**Comment by brunchboy** [comment]
For this level of exploratory discussion, please use the [Zulip discussion community](https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger), not issues on the project.
